name: tarkhub
services:
  tarkhub:
    container_name: tarkhub
    image: ghcr.io/mattiaginoble/tarkhub:latest
    ports:
      - 6969:6969
    env_file:
      - .env
    environment:
      - FORGE_API_KEY=${FORGE_API_KEY}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - SPT_VERSION=${SPT_VERSION:-latest}
      - FIKA_VERSION=${FIKA_VERSION:-latest}
      - PUBLIC_URL=${PUBLIC_URL}
      - ENABLE_PROXY_HEADERS=${ENABLE_PROXY_HEADERS}
    volumes:
      - server:/app/spt-server
      - user:/app/user
    restart: unless-stopped

volumes:
  server: null
  user: null
networks: {}
